{
 "title": "当前充电状态",
 "tags": [ "battery" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "车辆",
    "query": "SELECT\n    id as __value,\n    CASE WHEN COUNT(id) OVER (PARTITION BY name) > 1 AND name IS NOT NULL THEN CONCAT(name, ' - ', RIGHT(vin, 6)) ELSE COALESCE(name, CONCAT('VIN ', vin)) end as __text \nFROM cars\nORDER BY display_priority ASC, name ASC, vin ASC;"
   },
   {
    "name": "length_unit",
    "query": "select unit_of_length from settings limit 1;"
   },
   {
    "name": "temp_unit",
    "query": "select unit_of_temperature from settings limit 1;"
   },
   {
    "name": "BatteryCapacity",
    "query": "SELECT AVG(Capacity) AS CurrentCapacity FROM\n  (SELECT (100.0 * cp.charge_energy_added) / (GREATEST(1,MAX(usable_battery_level) - MIN(usable_battery_level))) AS Capacity\t\n    FROM charging_processes cp\n\t  INNER JOIN charges c ON cp.id = c.charging_process_id\n\t  WHERE cp.car_id = $car_id AND \n            cp.charge_energy_added >= (SELECT efficiency FROM cars WHERE id = 1) * 100.0\n    GROUP BY  cp.charge_energy_added, cp.end_date\n    ORDER BY cp.end_date DESC \n    LIMIT 5) AS lastEstimatedCapacity;"
   },
   {
    "name": "current_charge_time",
    "query": "SELECT (round(extract(epoch FROM start_date) - 10) * 1000) AS start_date_ts FROM charging_processes WHERE id = $charging_processes"
   },
   {
    "name": "charging_processes",
    "query": "SELECT id FROM charging_processes WHERE car_id = $car_id ORDER BY start_date DESC LIMIT 1"
   },
   {
    "name": "current_end_time",
    "query": "SELECT CASE WHEN end_date IS NULL THEN 'now&refresh=10s' ELSE CAST(round(extract(epoch FROM end_date) - 10) * 1000 AS VARCHAR(100)) END FROM charging_processes WHERE id = $charging_processes"
   },
   {
    "name": "map_url",
    "label": "地图源",
    "query": "OpenStreetMap : https://tile.openstreetmap.org/{z}/{x}/{y}.png,高德地图 : https://wprd01.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=7&x={x}&y={y}&z={z},高德卫星 : https://webst01.is.autonavi.com/appmaptile?style=6&x={x}&y={y}&z={z},谷歌地图 : https://mt1.google.com/vt/lyrs=m&x={x}&y={y}&z={z},谷歌卫星 : https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z},Carto 浅色 : https://cartodb-basemaps-c.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png"
   }
  ]
 },
 "panels": [
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "rawSql": "SELECT battery_level as \"电量[%]\" FROM charges c join charging_processes p ON p.id = c.charging_process_id WHERE $__timeFilter(date) AND p.car_id = $car_id ORDER BY c.ID DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "rawSql": "SELECT battery_level * $BatteryCapacity / 100 AS \"千瓦时\", $BatteryCapacity AS Total FROM charges c join charging_processes p ON p.id = c.charging_process_id WHERE $__timeFilter(date) AND p.car_id = $car_id ORDER BY c.ID DESC LIMIT 1"
    }
   ]
  },
  {
   "type": "text",
   "description": "充电时加载此仪表盘查看实时状态。打开后会自动每分钟刷新。",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": {
    "content": "<center>\n<img src=\"https://raw.githubusercontent.com/jheredianet/Teslamate-CustomGrafanaDashboards/main/screenshots/help/BatteryCharging.gif\"\nstyle=\"max-height: 125px\" />\n</center>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  start_date AS \"时间\",\n  start_km\nFROM drives\nWHERE\n  $__timeFilter(start_date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "充电量",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "kWh Added",
     "rawSql": "SELECT max(charge_energy_added) AS \"增加\" FROM charges WHERE charging_process_id = $charging_processes AND $__timeFilter(date)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE(g.name, CONCAT_WS(', ', COALESCE(addresses.name, CONCAT_WS(' ', addresses.road, addresses.house_number)), addresses.city)) FROM charging_processes c \tLEFT JOIN addresses ON addresses.id = c.address_id \tLEFT JOIN geofences g ON g.id = geofence_id WHERE \tc.id = $charging_processes"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "alias": "Power [kW]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "rawSql": "SELECT $__time(date), battery_level as \"电量[%]\", (case when charger_phases >= 1 then (case when charger_phases = 2 then 3 when charger_phases = 1 then 1 else charger_phases end) * charger_actual_current * charger_voltage / 1000.0 else charger_power end) AS \"功率 [kW]\", (case when battery_heater_on then 10 when battery_heater then 10 else 0 end) as \"电池加热器\" FROM charges c JOIN charging_processes p ON p.id = c.charging_process_id WHERE $__timeFilter(date) and p.car_id = $car_id ORDER BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "alias": "Real",
     "measurement": "km",
     "rawSql": " SELECT battery_level as \"起始电量\" FROM charges \twhere charging_process_id=$charging_processes \tORDER BY DATE ASC \tLIMIT 1"
    },
    {
     "rawSql": "SELECT battery_level - (SELECT battery_level AS \"增加\" FROM charges where charging_process_id=$charging_processes\tORDER BY DATE ASC \tLIMIT 1) as \"增加能量\" FROM charges c join charging_processes p ON p.id = c.charging_process_id WHERE $__timeFilter(date) AND p.car_id = $car_id ORDER BY c.ID DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "充电时间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "alias": "Elapsed Time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "WITH start_process AS (\n  SELECT date FROM charges\n  WHERE charging_process_id=$charging_processes\n  ORDER BY date ASC LIMIT 1\n)\nSELECT\n  CASE WHEN floor(secs / 3600) > 0 THEN floor(secs / 3600)::text || '时' ELSE '' END ||\n  CASE WHEN floor(secs::bigint % 3600 / 60) > 0 OR floor(secs / 3600) > 0\n       THEN floor(secs::bigint % 3600 / 60)::text || '分' ELSE '' END ||\n  floor(secs::bigint % 60)::text || '秒' AS \"已用时间\"\nFROM (\n  SELECT COALESCE(EXTRACT(EPOCH FROM (max(charges.date) - max(start_process.date)))::bigint, 0) AS secs\n  FROM charges, start_process\n  WHERE charges.charging_process_id = $charging_processes\n) sub"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(date),\n  lat_for_map('${map_url}', latitude, longitude) AS latitude,\n  lng_for_map('${map_url}', latitude, longitude) AS longitude\nFROM positions\nWHERE\n  car_id = $car_id AND\n  $__timeFilter(date)\nORDER BY\n  date ASC"
    }
   ]
  },
  {
   "title": "里程表",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "alias": "Real",
     "measurement": "km",
     "rawSql": "select $__time(date), convert_km(odometer::numeric, '$length_unit') AS \"里程表\" from positions where car_id = $car_id order by date desc limit 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Real",
     "measurement": "km",
     "rawSql": "SELECT convert_km(rated_battery_range_km, '$length_unit') as \"初始续航\" FROM charges WHERE charging_process_id = $charging_processes AND rated_battery_range_km IS NOT NULL AND $__timeFilter(date) ORDER BY date ASC LIMIT 1"
    },
    {
     "alias": "Real",
     "measurement": "km",
     "rawSql": "SELECT convert_km(rated_battery_range_km, '$length_unit') as \"额定续航\" FROM charges WHERE charging_process_id = $charging_processes AND rated_battery_range_km IS NOT NULL AND $__timeFilter(date) ORDER BY date DESC LIMIT 1"
    },
    {
     "alias": "Estimated",
     "measurement": "km",
     "rawSql": "SELECT $__timeGroupAlias(date,$__interval), avg(convert_km(est_battery_range_km, '$length_unit')) as \"预估续航\" FROM positions WHERE car_id = $car_id AND $__timeFilter(date) AND est_battery_range_km IS NOT NULL GROUP BY 1 ORDER BY 1 desc limit 1"
    }
   ]
  },
  {
   "title": "交流输入电流",
   "type": "stat",
   "description": "单位：A。仅显示交流充电器输入电流；TeslaMate 未记录真实直流电流，直流快充期间请查看功率和充入电量。",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH latest_charge AS (\n  SELECT\n    charger_power,\n    charger_phases,\n    charger_actual_current\n  FROM charges\n  WHERE charging_process_id = $charging_processes\n    AND $__timeFilter(date)\n  ORDER BY date DESC\n  LIMIT 1\n)\nSELECT\n  CASE\n    WHEN charger_power > 0\n      AND charger_phases >= 1\n      AND charger_actual_current > 0\n      THEN charger_actual_current\n    ELSE NULL\n  END AS \"当前\"\nFROM latest_charge"
    }
   ]
  },
  {
   "title": "交流输入电压",
   "type": "stat",
   "description": "单位：V。仅显示交流充电器输入电压；TeslaMate 未记录真实直流电压，直流快充期间请查看功率和充入电量。",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH latest_charge AS (\n  SELECT\n    charger_power,\n    charger_phases,\n    charger_voltage\n  FROM charges\n  WHERE charging_process_id = $charging_processes\n    AND $__timeFilter(date)\n  ORDER BY date DESC\n  LIMIT 1\n)\nSELECT\n  CASE\n    WHEN charger_power > 0\n      AND charger_phases >= 1\n      AND charger_voltage > 2\n      THEN charger_voltage\n    ELSE NULL\n  END AS \"电压\"\nFROM latest_charge"
    }
   ]
  },
  {
   "title": "平均功率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kW" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(case when charger_phases >= 1 then (case when charger_phases = 2 then 3 when charger_phases = 1 then 1 else charger_phases end) * charger_actual_current * charger_voltage / 1000.0 else charger_power end) AS \"功率\" FROM charges WHERE charging_process_id = $charging_processes AND $__timeFilter(date)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(convert_celsius(outside_temp, '$temp_unit')) as \"车外温度\" FROM charges WHERE charging_process_id = $charging_processes AND $__timeFilter(date)"
    },
    {
     "rawSql": "SELECT $__timeGroupAlias(date,$__interval), avg(convert_celsius(inside_temp, '$temp_unit')) AS \"车内温度\" FROM positions WHERE car_id = $car_id and inside_temp is not null AND $__timeFilter(date) GROUP BY 1 ORDER BY 1 "
    },
    {
     "rawSql": "SELECT \t$__timeGroupAlias(date,$__interval), \tavg(convert_celsius(driver_temp_setting, '$temp_unit')) as \"空调温度\" FROM positions WHERE driver_temp_setting IS NOT NULL AND car_id = $car_id AND $__timeFilter(date) GROUP BY 1 ORDER BY 1 "
    }
   ]
  }
 ]
}