{
 "title": "快充曲线图(按运营商)",
 "tags": [ "battery" ],
 "time": { "from": "now-1M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "车辆",
    "query": "SELECT\n    id as __value,\n    CASE WHEN COUNT(id) OVER (PARTITION BY name) > 1 AND name IS NOT NULL THEN CONCAT(name, ' - ', RIGHT(vin, 6)) ELSE COALESCE(name, CONCAT('VIN ', vin)) end as __text \nFROM cars\nORDER BY display_priority ASC, name ASC, vin ASC;"
   },
   {
    "name": "base_url",
    "label": "此部分需要配置名为\"家\"和\"公司\"的地理围栏并设置费用，以便准确计算充电成本。",
    "query": "select base_url from settings limit 1;"
   },
   { "name": "carrier", "label": "运营商" }
  ]
 },
 "panels": [
  {
   "title": "充电运营商包含: $carrier",
   "type": "xychart",
   "gridPos": { "h": 16, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  c.battery_level as \"电量 [%]\",\r\n  round(avg(c.charger_power), 0) AS \"功率 [kW]\",\r\n  c.charging_process_id as \"充电进程ID\",\r\n  COALESCE(g.name, a.name) || ' ' || to_char(c.date, 'YYYY-MM-dd') as \"充电\",\r\n  p.start_date as \"开始日期\",\r\n  p.end_date as \"结束日期\"\r\nFROM\r\n  charges c\r\nJOIN charging_processes p ON p.id = c.charging_process_id \r\nJOIN addresses a ON a.id = p.address_id\r\nLEFT JOIN geofences g ON g.id = p.geofence_id\r\nWHERE\r\n  $__timeFilter(date)\r\n AND p.car_id = $car_id\r\n AND c.fast_charger_present\r\n AND COALESCE(g.name, a.name) ILIKE '%$carrier%' \r\nGROUP BY c.battery_level, c.charging_process_id, a.name, g.name, p.start_date, p.end_date, to_char(c.date, 'YYYY-MM-dd')"
    },
    {
     "rawSql": "SELECT\n  c.battery_level as \"B - 电量 [%]\",\n  PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY charger_power) as \"B - 平均功率 [kW]\"\nFROM\n  charges c\nJOIN charging_processes p ON p.id = c.charging_process_id \nJOIN addresses a ON a.id = p.address_id\nLEFT JOIN geofences g ON g.id = p.geofence_id\nWHERE\n  $__timeFilter(date)\n AND p.car_id = $car_id\n AND c.fast_charger_present\n AND COALESCE(g.name, a.name) ILIKE '%$carrier%'\nGROUP BY c.battery_level"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 16, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\nSELECT\r\n  COALESCE(g.name, a.name) AS name\r\nFROM charging_processes p\r\n    LEFT JOIN charges c ON c.charging_process_id = p.id\r\n    LEFT JOIN addresses a ON a.id = p.address_id\r\n    LEFT JOIN geofences g ON g.id = p.geofence_id\r\nWHERE\r\n  p.car_id = $car_id \r\n  AND $__timeFilter(start_date)\r\n  AND c.fast_charger_present\r\n  AND COALESCE(g.name, a.name) ILIKE '%$carrier%' \r\nGROUP BY p.id, g.name, a.name\r\n)\r\nSELECT name AS \"充电运营商\" FROM data GROUP BY name\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "平均充电量 (kWh)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n AVG(p.charge_energy_added)\r\nFROM charging_processes p\r\n    LEFT JOIN charges c ON c.charging_process_id = p.id\r\n    LEFT JOIN addresses a ON a.id = p.address_id\r\n    LEFT JOIN geofences g ON g.id = p.geofence_id\r\nWHERE\r\n  p.car_id = $car_id \r\n  AND $__timeFilter(start_date)\r\n  AND c.fast_charger_present\r\n  AND COALESCE(g.name, a.name) ILIKE '%$carrier%' \r\nGROUP BY p.id"
    }
   ]
  },
  {
   "title": "平均耗电量 (kWh)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n AVG(p.charge_energy_used)\r\nFROM charging_processes p\r\n    LEFT JOIN charges c ON c.charging_process_id = p.id\r\n    LEFT JOIN addresses a ON a.id = p.address_id\r\n    LEFT JOIN geofences g ON g.id = p.geofence_id\r\nWHERE\r\n  p.car_id = $car_id \r\n  AND $__timeFilter(start_date)\r\n  AND c.fast_charger_present\r\n  AND COALESCE(g.name, a.name) ILIKE '%$carrier%' \r\nGROUP BY p.id"
    }
   ]
  },
  {
   "title": "平均时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "分钟" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n AVG(duration_min)\r\nFROM charging_processes p\r\n    LEFT JOIN charges c ON c.charging_process_id = p.id\r\n    LEFT JOIN addresses a ON a.id = p.address_id\r\n    LEFT JOIN geofences g ON g.id = p.geofence_id\r\nWHERE\r\n  p.car_id = $car_id \r\n  AND $__timeFilter(start_date)\r\n  AND c.fast_charger_present\r\n  AND COALESCE(g.name, a.name) ILIKE '%$carrier%' \r\n"
    }
   ]
  },
  {
   "title": "平均费用",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "元" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n AVG(effective_cost(p.id, p.cost))\r\nFROM charging_processes p\r\n    LEFT JOIN charges c ON c.charging_process_id = p.id\r\n    LEFT JOIN addresses a ON a.id = p.address_id\r\n    LEFT JOIN geofences g ON g.id = p.geofence_id\r\nWHERE\r\n  p.car_id = $car_id \r\n  AND $__timeFilter(start_date)\r\n  AND c.fast_charger_present\r\n  AND COALESCE(g.name, a.name) ILIKE '%$carrier%' \r\nGROUP BY p.id"
    }
   ]
  },
  {
   "title": "平均每度电费用",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "元/度" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\nSELECT\r\n AVG(p.charge_energy_used) AS charge_energy_used, AVG(effective_cost(p.id, p.cost)) AS cost \r\nFROM charging_processes p\r\n    LEFT JOIN charges c ON c.charging_process_id = p.id\r\n    LEFT JOIN addresses a ON a.id = p.address_id\r\n    LEFT JOIN geofences g ON g.id = p.geofence_id\r\nWHERE\r\n  p.car_id = $car_id \r\n  AND $__timeFilter(start_date)\r\n  AND c.fast_charger_present\r\n  AND COALESCE(g.name, a.name) ILIKE '%$carrier%' \r\nGROUP BY p.id\r\n)\r\nSELECT AVG(cost) / AVG(charge_energy_used) cost_kwh  FROM data"
    }
   ]
  },
  {
   "title": "帮助",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
     "options": {
      "content": "#### 按运营商分组的直流充电曲线\n\n要使用本仪表盘分析数据，需要先在 TeslaMate 中添加包含\n充电运营商名称的**地理围栏**，或者定期编辑数据库中\naddresses 表的 name 字段（即地点名称），在其中加入\n运营商名称。\n\n例如，如果 **TeslaMate** 将地点识别为 *\"朝阳路充电站\"*，\n可以将其修改为 *\"朝阳路充电站 - 特来电\"* 或\n*\"特来电 朝阳路充电站\"*，然后在上方文本框中输入 **特来电**，\n即可筛选该运营商所有充电会话的充电曲线。\n\n常见国内充电运营商：特来电、星星充电、国家电网、小桔充电、\n蔚来超充、特斯拉超充等。\n\n**注**：addresses 和 name 是 PostgreSQL 数据库的表名和字段名，\n操作数据库时必须使用英文原名。"
     },
     "targets": [
      {
       "rawSql": "SELECT\n  start_date AS \"时间\",\n  start_km\nFROM drives\nWHERE\n  $__timeFilter(start_date)\nORDER BY 1"
      }
     ]
    }
   ]
  }
 ]
}