apiVersion: 1

datasources:
  - name: TeslaMate
    type: grafana-postgresql-datasource
    uid: TeslaMate
    access: proxy
    url: ${DATABASE_HOST}:${DATABASE_PORT}
    user: ${DATABASE_USER}
    basicAuth: false
    withCredentials: false
    isDefault: true
    secureJsonData:
      password: ${DATABASE_PASS}
    jsonData:
      database: ${DATABASE_NAME}
      sslmode: ${DATABASE_SSL_MODE}
      postgresVersion: 1500
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      timescaledb: false
    version: 1
    editable: false
